base_url = "https://hannover.freifunk.net/blog/"
compile_sass = true
build_search_index = false
generate_feeds = true
author = "Freifunk Hannover"
default_language = "de"
minify_html = true
hard_link_static = true
generate_sitemap = false
generate_robots_txt = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
